//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_candle_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public string direction { get; set; }
        public string size { get; set; }
        public string candle { get; set; }
    }
}
