//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_raw
    {
        public string TICKER { get; set; }
        public string PER { get; set; }
        public System.DateTime DATE { get; set; }
        public byte TIME { get; set; }
        public Nullable<double> OPEN { get; set; }
        public Nullable<double> HIGH { get; set; }
        public Nullable<double> LOW { get; set; }
        public Nullable<double> CLOSE { get; set; }
        public Nullable<int> VOL { get; set; }
        public Nullable<byte> OPENINT { get; set; }
    }
}
