//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_analysis_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> price_pre { get; set; }
        public Nullable<double> price_chg_perc { get; set; }
        public Nullable<double> sma3 { get; set; }
        public Nullable<double> sma5 { get; set; }
        public Nullable<double> sma8 { get; set; }
        public Nullable<double> sma15 { get; set; }
        public Nullable<double> sma20 { get; set; }
        public Nullable<double> sma33 { get; set; }
        public Nullable<double> sma45 { get; set; }
        public Nullable<double> sma60 { get; set; }
        public Nullable<double> sma120 { get; set; }
        public Nullable<double> sma360 { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> volume_pre { get; set; }
        public Nullable<double> volume_chg_perc { get; set; }
    }
}
