//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_close_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> sma_005 { get; set; }
        public Nullable<double> sma_010 { get; set; }
        public Nullable<double> sma_020 { get; set; }
        public Nullable<double> sma_030 { get; set; }
        public Nullable<double> sma_060 { get; set; }
        public Nullable<double> sma_120 { get; set; }
        public Nullable<double> sma_240 { get; set; }
        public string direction { get; set; }
        public Nullable<double> head { get; set; }
        public Nullable<double> center { get; set; }
        public Nullable<double> tail { get; set; }
        public string candle { get; set; }
        public Nullable<double> size_sma5 { get; set; }
        public Nullable<double> size_sma10 { get; set; }
        public Nullable<double> size_sma20 { get; set; }
        public Nullable<double> size_sma30 { get; set; }
        public Nullable<double> size_sma60 { get; set; }
        public Nullable<double> size_sma120 { get; set; }
        public Nullable<double> size_sma240 { get; set; }
    }
}
