//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class sector_v1
    {
        public string sector { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> price_chg { get; set; }
        public Nullable<double> idx_chg { get; set; }
        public Nullable<double> strong { get; set; }
        public Nullable<double> strong_sma5 { get; set; }
    }
}
