//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class watch_list_v1
    {
        public string symbol { get; set; }
        public string watch_type { get; set; }
        public string company { get; set; }
        public string industry { get; set; }
        public string sector { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> last_earning { get; set; }
    }
}
