//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekly_analysis
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public double price_high { get; set; }
        public double price_low { get; set; }
        public double price_open { get; set; }
        public double price_close { get; set; }
        public Nullable<double> price_chg_perc { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> volume_chg_perc { get; set; }
        public Nullable<double> price_high_chg_perc { get; set; }
        public Nullable<double> price_low_chg_perc { get; set; }
    }
}
