CREATE TABLE [dbo].[daily_strong] (
    [symbol]         NVARCHAR (50) NOT NULL,
    [date_hist]      DATE          NOT NULL,
    [price]          FLOAT (53)    NULL,
    [price_chg_perc] FLOAT (53)    NULL,
    [sma5_chg_perc]  FLOAT (53)    NULL,
    [spy_price]      FLOAT (53)    NULL,
    [spy_chg]        FLOAT (53)    NULL,
    [spy_sma5]       FLOAT (53)    NULL,
    [spy_diff]       FLOAT (53)    NULL,
    [spy_diff_sma5]  FLOAT (53)    NULL,
    [qqq_price]      FLOAT (53)    NULL,
    [qqq_chg]        FLOAT (53)    NULL,
    [qqq_sma5]       FLOAT (53)    NULL,
    [qqq_diff]       FLOAT (53)    NULL,
    [qqq_diff_sma5]  FLOAT (53)    NULL,
    [dia_price]      FLOAT (53)    NULL,
    [dia_chg]        FLOAT (53)    NULL,
    [dia_sma5]       FLOAT (53)    NULL,
    [dia_diff]       FLOAT (53)    NULL,
    [dia_diff_sma5]  FLOAT (53)    NULL,
    [idx_diff]       FLOAT (53)    NULL,
    [idx_diff_sma5]  FLOAT (53)    NULL,
    [idx_chg]        FLOAT (53)    NULL,
    [idx_price]      FLOAT (53)    NULL,
    [idx_sma5]       FLOAT (53)    NULL,
    [sma5]           FLOAT (53)    NULL,
    CONSTRAINT [PK_daily_strong] PRIMARY KEY CLUSTERED ([symbol] ASC, [date_hist] ASC)
);

