CREATE TABLE [dbo].[fundamental] (
    [symbol]                   NVARCHAR (50) NOT NULL,
    [date_hist]                DATE          NOT NULL,
    [date_fiscal]              DATE          NOT NULL,
    [eps]                      FLOAT (53)    NULL,
    [perc_eps]                 FLOAT (53)    NULL,
    [perc_eps_1year]           FLOAT (53)    NULL,
    [perc_eps_3year]           FLOAT (53)    NULL,
    [est]                      FLOAT (53)    NULL,
    [perc_est]                 FLOAT (53)    NULL,
    [perc_est_1year]           FLOAT (53)    NULL,
    [perc_est_3year]           FLOAT (53)    NULL,
    [surprise]                 FLOAT (53)    NULL,
    [surprise_1year]           FLOAT (53)    NULL,
    [surprise_3year]           FLOAT (53)    NULL,
    [perc_after_expense]       FLOAT (53)    NULL,
    [perc_after_expense_1year] FLOAT (53)    NULL,
    [perc_after_expense_3year] FLOAT (53)    NULL,
    [perc_profit]              FLOAT (53)    NULL,
    [perc_profit_1year]        FLOAT (53)    NULL,
    [perc_profit_3year]        FLOAT (53)    NULL,
    [perc_total]               FLOAT (53)    NULL,
    [perc_total_1year]         FLOAT (53)    NULL,
    [perc_total_3year]         FLOAT (53)    NULL,
    [eps_close_rate]           FLOAT (53)    NULL,
    [pre_30]                   FLOAT (53)    NULL,
    [pre_20]                   FLOAT (53)    NULL,
    [pre_10]                   FLOAT (53)    NULL,
    [pre_5]                    FLOAT (53)    NULL,
    [pre_3]                    FLOAT (53)    NULL,
    [pre_1]                    FLOAT (53)    NULL,
    [next_1]                   FLOAT (53)    NULL,
    [next_3]                   FLOAT (53)    NULL,
    [next_5]                   FLOAT (53)    NULL,
    [next_10]                  FLOAT (53)    NULL,
    [next_20]                  FLOAT (53)    NULL,
    [next_30]                  FLOAT (53)    NULL,
    CONSTRAINT [PK_fundamental] PRIMARY KEY CLUSTERED ([symbol] ASC, [date_hist] ASC)
);

