CREATE TABLE [dbo].[income] (
    [symbol]                            NVARCHAR (50) NOT NULL,
    [fiscalDateEnding]                  DATE          NOT NULL,
    [reportedCurrency]                  NVARCHAR (50) NULL,
    [totalRevenue]                      FLOAT (53)    NULL,
    [totalOperatingExpense]             FLOAT (53)    NULL,
    [costOfRevenue]                     FLOAT (53)    NULL,
    [grossProfit]                       FLOAT (53)    NULL,
    [ebit]                              FLOAT (53)    NULL,
    [netIncome]                         FLOAT (53)    NULL,
    [researchAndDevelopment]            FLOAT (53)    NULL,
    [effectOfAccountingCharges]         FLOAT (53)    NULL,
    [incomeBeforeTax]                   FLOAT (53)    NULL,
    [minorityInterest]                  FLOAT (53)    NULL,
    [sellingGeneralAdministrative]      FLOAT (53)    NULL,
    [otherNonOperatingIncome]           FLOAT (53)    NULL,
    [operatingIncome]                   FLOAT (53)    NULL,
    [otherOperatingExpense]             FLOAT (53)    NULL,
    [interestExpense]                   FLOAT (53)    NULL,
    [taxProvision]                      NVARCHAR (50) NULL,
    [interestIncome]                    NVARCHAR (50) NULL,
    [netInterestIncome]                 NVARCHAR (50) NULL,
    [extraordinaryItems]                FLOAT (53)    NULL,
    [nonRecurring]                      FLOAT (53)    NULL,
    [otherItems]                        FLOAT (53)    NULL,
    [incomeTaxExpense]                  FLOAT (53)    NULL,
    [totalOtherIncomeExpense]           FLOAT (53)    NULL,
    [discontinuedOperations]            FLOAT (53)    NULL,
    [netIncomeFromContinuingOperations] FLOAT (53)    NULL,
    [netIncomeApplicableToCommonShares] FLOAT (53)    NULL,
    [preferredStockAndOtherAdjustments] NVARCHAR (50) NULL,
    CONSTRAINT [PK_income] PRIMARY KEY CLUSTERED ([symbol] ASC, [fiscalDateEnding] ASC)
);

