//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_strong_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> price_chg_perc { get; set; }
        public Nullable<double> sma5 { get; set; }
        public Nullable<double> sma5_chg_perc { get; set; }
        public Nullable<double> spy_price { get; set; }
        public Nullable<double> spy_chg { get; set; }
        public Nullable<double> spy_sma5 { get; set; }
        public Nullable<double> spy_diff { get; set; }
        public Nullable<double> spy_diff_sma5 { get; set; }
        public Nullable<double> qqq_price { get; set; }
        public Nullable<double> qqq_chg { get; set; }
        public Nullable<double> qqq_sma5 { get; set; }
        public Nullable<double> qqq_diff { get; set; }
        public Nullable<double> qqq_diff_sma5 { get; set; }
        public Nullable<double> dia_price { get; set; }
        public Nullable<double> dia_chg { get; set; }
        public Nullable<double> dia_sma5 { get; set; }
        public Nullable<double> dia_diff { get; set; }
        public Nullable<double> dia_diff_sma5 { get; set; }
        public Nullable<double> idx_price { get; set; }
        public Nullable<double> idx_sma5 { get; set; }
        public Nullable<double> idx_chg { get; set; }
        public Nullable<double> idx_diff { get; set; }
        public Nullable<double> idx_diff_sma5 { get; set; }
    }
}
