//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_sma5
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> price_pre { get; set; }
        public Nullable<double> price_chg_perc { get; set; }
        public Nullable<double> sma5 { get; set; }
        public Nullable<double> sma5_pre { get; set; }
        public Nullable<double> sma5_chg_perc { get; set; }
    }
}
