//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_vol_sma10_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> volume_pre { get; set; }
        public Nullable<double> volume_chg_perc { get; set; }
        public Nullable<double> sma10 { get; set; }
        public Nullable<double> sma10_pre { get; set; }
        public Nullable<double> sma10_chg_perc { get; set; }
    }
}
