//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_volume_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> sma_005 { get; set; }
        public Nullable<double> sma_010 { get; set; }
        public Nullable<double> sma_020 { get; set; }
        public Nullable<double> sma_030 { get; set; }
        public Nullable<double> sma_060 { get; set; }
        public Nullable<double> sma_120 { get; set; }
        public Nullable<double> sma_240 { get; set; }
        public Nullable<double> volume_pre { get; set; }
    }
}
