//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_close
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public Nullable<double> SMA_005 { get; set; }
        public Nullable<double> SMA_010 { get; set; }
        public Nullable<double> SMA_020 { get; set; }
        public Nullable<double> SMA_030 { get; set; }
        public Nullable<double> SMA_060 { get; set; }
        public Nullable<double> SMA_120 { get; set; }
        public Nullable<double> SMA_240 { get; set; }
        public Nullable<double> price { get; set; }
    }
}
