//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_source
    {
        public string symbol { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> open { get; set; }
        public Nullable<double> close { get; set; }
        public Nullable<double> adjusted_close { get; set; }
        public Nullable<double> high { get; set; }
        public Nullable<double> low { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> dividend_amount { get; set; }
        public Nullable<double> split_coefficient { get; set; }
    }
}
