//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class earning
    {
        public string symbol { get; set; }
        public System.DateTime fiscalDateEnding { get; set; }
        public Nullable<System.DateTime> reportedDate { get; set; }
        public Nullable<double> reportedEPS { get; set; }
        public Nullable<double> estimatedEPS { get; set; }
        public Nullable<double> surprise { get; set; }
        public Nullable<double> surprisePercentage { get; set; }
    }
}
