//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class fundamental_v1
    {
        public string symbol { get; set; }
        public System.DateTime date_hist { get; set; }
        public System.DateTime date_fiscal { get; set; }
        public Nullable<double> eps { get; set; }
        public Nullable<double> perc_eps { get; set; }
        public Nullable<double> perc_eps_1year { get; set; }
        public Nullable<double> perc_eps_3year { get; set; }
        public Nullable<double> est { get; set; }
        public Nullable<double> perc_est { get; set; }
        public Nullable<double> perc_est_1year { get; set; }
        public Nullable<double> perc_est_3year { get; set; }
        public Nullable<double> surprise { get; set; }
        public Nullable<double> surprise_1year { get; set; }
        public Nullable<double> surprise_3year { get; set; }
        public Nullable<double> perc_after_expense { get; set; }
        public Nullable<double> perc_after_expense_1year { get; set; }
        public Nullable<double> perc_after_expense_3year { get; set; }
        public Nullable<double> perc_profit { get; set; }
        public Nullable<double> perc_profit_1year { get; set; }
        public Nullable<double> perc_profit_3year { get; set; }
        public Nullable<double> perc_total { get; set; }
        public Nullable<double> perc_total_1year { get; set; }
        public Nullable<double> perc_total_3year { get; set; }
        public Nullable<double> eps_close_rate { get; set; }
        public Nullable<double> pre_30 { get; set; }
        public Nullable<double> pre_20 { get; set; }
        public Nullable<double> pre_10 { get; set; }
        public Nullable<double> pre_5 { get; set; }
        public Nullable<double> pre_3 { get; set; }
        public Nullable<double> pre_1 { get; set; }
        public Nullable<double> next_1 { get; set; }
        public Nullable<double> next_3 { get; set; }
        public Nullable<double> next_5 { get; set; }
        public Nullable<double> next_10 { get; set; }
        public Nullable<double> next_20 { get; set; }
        public Nullable<double> next_30 { get; set; }
    }
}
