//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class income
    {
        public string symbol { get; set; }
        public System.DateTime fiscalDateEnding { get; set; }
        public string reportedCurrency { get; set; }
        public Nullable<double> totalRevenue { get; set; }
        public Nullable<double> totalOperatingExpense { get; set; }
        public Nullable<double> costOfRevenue { get; set; }
        public Nullable<double> grossProfit { get; set; }
        public Nullable<double> ebit { get; set; }
        public Nullable<double> netIncome { get; set; }
        public Nullable<double> researchAndDevelopment { get; set; }
        public Nullable<double> effectOfAccountingCharges { get; set; }
        public Nullable<double> incomeBeforeTax { get; set; }
        public Nullable<double> minorityInterest { get; set; }
        public Nullable<double> sellingGeneralAdministrative { get; set; }
        public Nullable<double> otherNonOperatingIncome { get; set; }
        public Nullable<double> operatingIncome { get; set; }
        public Nullable<double> otherOperatingExpense { get; set; }
        public Nullable<double> interestExpense { get; set; }
        public string taxProvision { get; set; }
        public string interestIncome { get; set; }
        public string netInterestIncome { get; set; }
        public Nullable<double> extraordinaryItems { get; set; }
        public Nullable<double> nonRecurring { get; set; }
        public Nullable<double> otherItems { get; set; }
        public Nullable<double> incomeTaxExpense { get; set; }
        public Nullable<double> totalOtherIncomeExpense { get; set; }
        public Nullable<double> discontinuedOperations { get; set; }
        public Nullable<double> netIncomeFromContinuingOperations { get; set; }
        public Nullable<double> netIncomeApplicableToCommonShares { get; set; }
        public string preferredStockAndOtherAdjustments { get; set; }
    }
}
