//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_history
    {
        public int HIST_ID { get; set; }
        public System.DateTime HIST_DTTM { get; set; }
        public System.DateTime START_DTTM { get; set; }
        public System.DateTime END_DTTM { get; set; }
        public string PASS_LIST { get; set; }
        public int FILTER_OPTION { get; set; }
        public string att1 { get; set; }
        public string att2 { get; set; }
        public string att3 { get; set; }
        public string att4 { get; set; }
        public string att5 { get; set; }
        public string option_desc { get; set; }
    }
}
