//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_history_v1
    {
        public int HIST_ID { get; set; }
        public System.DateTime HIST_DTTM { get; set; }
        public System.DateTime START_DTTM { get; set; }
        public System.DateTime END_DTTM { get; set; }
        public string PASS_LIST { get; set; }
        public int FILTER_OPTION { get; set; }
        public string att1 { get; set; }
        public string att2 { get; set; }
        public string att3 { get; set; }
        public string att4 { get; set; }
        public string att5 { get; set; }
        public string option_desc { get; set; }
        public Nullable<int> ranking { get; set; }
        public Nullable<double> ratio1 { get; set; }
        public Nullable<double> ratio2 { get; set; }
        public Nullable<double> rate_5 { get; set; }
        public Nullable<double> rate_10 { get; set; }
        public Nullable<double> rate_15 { get; set; }
        public Nullable<double> rate_20 { get; set; }
        public Nullable<double> rate_40 { get; set; }
        public Nullable<double> rate_60 { get; set; }
    }
}
