//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class simul_header
    {
        public int simul_header_id { get; set; }
        public string simul_name { get; set; }
        public Nullable<System.DateTime> start_dttm { get; set; }
        public Nullable<System.DateTime> end_dttm { get; set; }
        public Nullable<double> ratio1 { get; set; }
        public Nullable<double> ratio2 { get; set; }
        public Nullable<double> rate_5 { get; set; }
        public Nullable<double> rate_10 { get; set; }
        public Nullable<double> rate_15 { get; set; }
        public Nullable<double> rate_20 { get; set; }
        public Nullable<double> rate_40 { get; set; }
        public Nullable<double> rate_60 { get; set; }
    }
}
