//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class stockEntity : DbContext
    {
        public stockEntity()
            : base("name=stockEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<daily_analysis> daily_analysis { get; set; }
        public virtual DbSet<daily_close> daily_close { get; set; }
        public virtual DbSet<daily_history> daily_history { get; set; }
        public virtual DbSet<daily_sma5> daily_sma5 { get; set; }
        public virtual DbSet<daily_source> daily_source { get; set; }
        public virtual DbSet<daily_strong> daily_strong { get; set; }
        public virtual DbSet<daily_volume> daily_volume { get; set; }
        public virtual DbSet<earning> earning { get; set; }
        public virtual DbSet<fundamental> fundamental { get; set; }
        public virtual DbSet<income> income { get; set; }
        public virtual DbSet<list_history> list_history { get; set; }
        public virtual DbSet<lookup> lookup { get; set; }
        public virtual DbSet<prediction> prediction { get; set; }
        public virtual DbSet<prediction_history> prediction_history { get; set; }
        public virtual DbSet<simul_header> simul_header { get; set; }
        public virtual DbSet<simul_tests> simul_tests { get; set; }
        public virtual DbSet<symbol_att> symbol_att { get; set; }
        public virtual DbSet<test_plan> test_plan { get; set; }
        public virtual DbSet<watch_list> watch_list { get; set; }
        public virtual DbSet<api> api { get; set; }
        public virtual DbSet<daily_avg> daily_avg { get; set; }
        public virtual DbSet<daily_high> daily_high { get; set; }
        public virtual DbSet<daily_industry> daily_industry { get; set; }
        public virtual DbSet<daily_low> daily_low { get; set; }
        public virtual DbSet<daily_open> daily_open { get; set; }
        public virtual DbSet<daily_sector> daily_sector { get; set; }
        public virtual DbSet<daily_analysis_v1> daily_analysis_v1 { get; set; }
        public virtual DbSet<daily_candle_v1> daily_candle_v1 { get; set; }
        public virtual DbSet<daily_close_v1> daily_close_v1 { get; set; }
        public virtual DbSet<daily_sma5_v1> daily_sma5_v1 { get; set; }
        public virtual DbSet<daily_strong_v1> daily_strong_v1 { get; set; }
        public virtual DbSet<daily_v1> daily_v1 { get; set; }
        public virtual DbSet<daily_vol_sma10_v1> daily_vol_sma10_v1 { get; set; }
        public virtual DbSet<daily_vol_sma5_v1> daily_vol_sma5_v1 { get; set; }
        public virtual DbSet<daily_volume_v1> daily_volume_v1 { get; set; }
        public virtual DbSet<fundamental_v1> fundamental_v1 { get; set; }
        public virtual DbSet<industry_v1> industry_v1 { get; set; }
        public virtual DbSet<list_history_v1> list_history_v1 { get; set; }
        public virtual DbSet<sector_v1> sector_v1 { get; set; }
        public virtual DbSet<watch_list_v1> watch_list_v1 { get; set; }
    
        public virtual ObjectResult<filter_main_Result> filter_main(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, Nullable<int> option, string passing_list, string passing_symbols, string att1, string att2, string att3, string att4, string att5, string description)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var optionParameter = option.HasValue ?
                new ObjectParameter("option", option) :
                new ObjectParameter("option", typeof(int));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var passing_symbolsParameter = passing_symbols != null ?
                new ObjectParameter("passing_symbols", passing_symbols) :
                new ObjectParameter("passing_symbols", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filter_main_Result>("filter_main", start_dttmParameter, end_dttmParameter, optionParameter, passing_listParameter, passing_symbolsParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, descriptionParameter);
        }
    
        public virtual int filter_simul(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("filter_simul", start_dttmParameter, end_dttmParameter);
        }
    
        public virtual ObjectResult<filter_simul_header_Result> filter_simul_header(Nullable<System.DateTime> end_dttm)
        {
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filter_simul_header_Result>("filter_simul_header", end_dttmParameter);
        }
    
        public virtual int filter_simul_summary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("filter_simul_summary");
        }
    
        public virtual ObjectResult<get_Stat_history_Result> get_Stat_history(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, Nullable<int> hist_count, string final_only)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var hist_countParameter = hist_count.HasValue ?
                new ObjectParameter("hist_count", hist_count) :
                new ObjectParameter("hist_count", typeof(int));
    
            var final_onlyParameter = final_only != null ?
                new ObjectParameter("final_only", final_only) :
                new ObjectParameter("final_only", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Stat_history_Result>("get_Stat_history", start_dttmParameter, end_dttmParameter, hist_countParameter, final_onlyParameter);
        }
    
        public virtual int option_01(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_01", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_02(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_02", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_03(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_03", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_04(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_04", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_05(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_05", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_06(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_06", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_07(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_07", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_08(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_08", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_09(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_09", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_10(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_10", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_11(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_11", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_12(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_12", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_13(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_13", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_14(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_14", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_15(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_15", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_16(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_16", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_17(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_17", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_18(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_18", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_19(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_19", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_20(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_20", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int option_99(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, string passing_list, string att1, string att2, string att3, string att4, string att5, ObjectParameter option_desc)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("option_99", start_dttmParameter, end_dttmParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_desc);
        }
    
        public virtual int process_analysis(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("symbol", symbol) :
                new ObjectParameter("symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_analysis", symbolParameter);
        }
    
        public virtual int process_history(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("symbol", symbol) :
                new ObjectParameter("symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_history", symbolParameter);
        }
    
        public virtual int process_rsi_detail(string symbol, Nullable<System.DateTime> last_ran, string table_name, string col_name, Nullable<int> days)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("symbol", symbol) :
                new ObjectParameter("symbol", typeof(string));
    
            var last_ranParameter = last_ran.HasValue ?
                new ObjectParameter("last_ran", last_ran) :
                new ObjectParameter("last_ran", typeof(System.DateTime));
    
            var table_nameParameter = table_name != null ?
                new ObjectParameter("table_name", table_name) :
                new ObjectParameter("table_name", typeof(string));
    
            var col_nameParameter = col_name != null ?
                new ObjectParameter("col_name", col_name) :
                new ObjectParameter("col_name", typeof(string));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_rsi_detail", symbolParameter, last_ranParameter, table_nameParameter, col_nameParameter, daysParameter);
        }
    
        public virtual int process_sma_detail(string symbol, Nullable<System.DateTime> last_ran, string table_name, string col_name, Nullable<int> days)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("symbol", symbol) :
                new ObjectParameter("symbol", typeof(string));
    
            var last_ranParameter = last_ran.HasValue ?
                new ObjectParameter("last_ran", last_ran) :
                new ObjectParameter("last_ran", typeof(System.DateTime));
    
            var table_nameParameter = table_name != null ?
                new ObjectParameter("table_name", table_name) :
                new ObjectParameter("table_name", typeof(string));
    
            var col_nameParameter = col_name != null ?
                new ObjectParameter("col_name", col_name) :
                new ObjectParameter("col_name", typeof(string));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_sma_detail", symbolParameter, last_ranParameter, table_nameParameter, col_nameParameter, daysParameter);
        }
    
        public virtual int process_volume(string symbol)
        {
            var symbolParameter = symbol != null ?
                new ObjectParameter("symbol", symbol) :
                new ObjectParameter("symbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_volume", symbolParameter);
        }
    
        public virtual int sp_add_list_history(Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, Nullable<int> option, string passing_list, string att1, string att2, string att3, string att4, string att5, string option_desc, string description, ObjectParameter hist_id)
        {
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var optionParameter = option.HasValue ?
                new ObjectParameter("option", option) :
                new ObjectParameter("option", typeof(int));
    
            var passing_listParameter = passing_list != null ?
                new ObjectParameter("passing_list", passing_list) :
                new ObjectParameter("passing_list", typeof(string));
    
            var att1Parameter = att1 != null ?
                new ObjectParameter("att1", att1) :
                new ObjectParameter("att1", typeof(string));
    
            var att2Parameter = att2 != null ?
                new ObjectParameter("att2", att2) :
                new ObjectParameter("att2", typeof(string));
    
            var att3Parameter = att3 != null ?
                new ObjectParameter("att3", att3) :
                new ObjectParameter("att3", typeof(string));
    
            var att4Parameter = att4 != null ?
                new ObjectParameter("att4", att4) :
                new ObjectParameter("att4", typeof(string));
    
            var att5Parameter = att5 != null ?
                new ObjectParameter("att5", att5) :
                new ObjectParameter("att5", typeof(string));
    
            var option_descParameter = option_desc != null ?
                new ObjectParameter("option_desc", option_desc) :
                new ObjectParameter("option_desc", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_list_history", start_dttmParameter, end_dttmParameter, optionParameter, passing_listParameter, att1Parameter, att2Parameter, att3Parameter, att4Parameter, att5Parameter, option_descParameter, descriptionParameter, hist_id);
        }
    
        public virtual int sp_generate_idx()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_generate_idx");
        }
    
        public virtual ObjectResult<sp_get_prediction_history_Result> sp_get_prediction_history(Nullable<int> hist_id)
        {
            var hist_idParameter = hist_id.HasValue ?
                new ObjectParameter("hist_id", hist_id) :
                new ObjectParameter("hist_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_prediction_history_Result>("sp_get_prediction_history", hist_idParameter);
        }
    
        public virtual int sp_prediction_history_cleanup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_prediction_history_cleanup");
        }
    
        public virtual int sp_simul_test(Nullable<int> simul_header_id, Nullable<int> hist_id, string plan_name, string plan_desc, Nullable<int> filter_option, Nullable<int> week_no, Nullable<System.DateTime> start_dttm, Nullable<System.DateTime> end_dttm, Nullable<double> ratio1, Nullable<double> ratio2, Nullable<double> rate_5, Nullable<double> rate_10, Nullable<double> rate_15, Nullable<double> rate_20, Nullable<double> rate_40, Nullable<double> rate_60)
        {
            var simul_header_idParameter = simul_header_id.HasValue ?
                new ObjectParameter("simul_header_id", simul_header_id) :
                new ObjectParameter("simul_header_id", typeof(int));
    
            var hist_idParameter = hist_id.HasValue ?
                new ObjectParameter("hist_id", hist_id) :
                new ObjectParameter("hist_id", typeof(int));
    
            var plan_nameParameter = plan_name != null ?
                new ObjectParameter("plan_name", plan_name) :
                new ObjectParameter("plan_name", typeof(string));
    
            var plan_descParameter = plan_desc != null ?
                new ObjectParameter("plan_desc", plan_desc) :
                new ObjectParameter("plan_desc", typeof(string));
    
            var filter_optionParameter = filter_option.HasValue ?
                new ObjectParameter("filter_option", filter_option) :
                new ObjectParameter("filter_option", typeof(int));
    
            var week_noParameter = week_no.HasValue ?
                new ObjectParameter("week_no", week_no) :
                new ObjectParameter("week_no", typeof(int));
    
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var end_dttmParameter = end_dttm.HasValue ?
                new ObjectParameter("end_dttm", end_dttm) :
                new ObjectParameter("end_dttm", typeof(System.DateTime));
    
            var ratio1Parameter = ratio1.HasValue ?
                new ObjectParameter("ratio1", ratio1) :
                new ObjectParameter("ratio1", typeof(double));
    
            var ratio2Parameter = ratio2.HasValue ?
                new ObjectParameter("ratio2", ratio2) :
                new ObjectParameter("ratio2", typeof(double));
    
            var rate_5Parameter = rate_5.HasValue ?
                new ObjectParameter("rate_5", rate_5) :
                new ObjectParameter("rate_5", typeof(double));
    
            var rate_10Parameter = rate_10.HasValue ?
                new ObjectParameter("rate_10", rate_10) :
                new ObjectParameter("rate_10", typeof(double));
    
            var rate_15Parameter = rate_15.HasValue ?
                new ObjectParameter("rate_15", rate_15) :
                new ObjectParameter("rate_15", typeof(double));
    
            var rate_20Parameter = rate_20.HasValue ?
                new ObjectParameter("rate_20", rate_20) :
                new ObjectParameter("rate_20", typeof(double));
    
            var rate_40Parameter = rate_40.HasValue ?
                new ObjectParameter("rate_40", rate_40) :
                new ObjectParameter("rate_40", typeof(double));
    
            var rate_60Parameter = rate_60.HasValue ?
                new ObjectParameter("rate_60", rate_60) :
                new ObjectParameter("rate_60", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_simul_test", simul_header_idParameter, hist_idParameter, plan_nameParameter, plan_descParameter, filter_optionParameter, week_noParameter, start_dttmParameter, end_dttmParameter, ratio1Parameter, ratio2Parameter, rate_5Parameter, rate_10Parameter, rate_15Parameter, rate_20Parameter, rate_40Parameter, rate_60Parameter);
        }
    
        public virtual int sp_simul_test_delete(Nullable<int> simul_header_id)
        {
            var simul_header_idParameter = simul_header_id.HasValue ?
                new ObjectParameter("simul_header_id", simul_header_id) :
                new ObjectParameter("simul_header_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_simul_test_delete", simul_header_idParameter);
        }
    
        public virtual int sp_simulation(string symbols, Nullable<System.DateTime> start_dttm, Nullable<double> drop_limit_perc, Nullable<double> sell_limit_perc, Nullable<int> max_days_hold, string show_detail)
        {
            var symbolsParameter = symbols != null ?
                new ObjectParameter("symbols", symbols) :
                new ObjectParameter("symbols", typeof(string));
    
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var drop_limit_percParameter = drop_limit_perc.HasValue ?
                new ObjectParameter("drop_limit_perc", drop_limit_perc) :
                new ObjectParameter("drop_limit_perc", typeof(double));
    
            var sell_limit_percParameter = sell_limit_perc.HasValue ?
                new ObjectParameter("sell_limit_perc", sell_limit_perc) :
                new ObjectParameter("sell_limit_perc", typeof(double));
    
            var max_days_holdParameter = max_days_hold.HasValue ?
                new ObjectParameter("max_days_hold", max_days_hold) :
                new ObjectParameter("max_days_hold", typeof(int));
    
            var show_detailParameter = show_detail != null ?
                new ObjectParameter("show_detail", show_detail) :
                new ObjectParameter("show_detail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_simulation", symbolsParameter, start_dttmParameter, drop_limit_percParameter, sell_limit_percParameter, max_days_holdParameter, show_detailParameter);
        }
    
        public virtual int XXX_sp_weekly_v1(string symbols, Nullable<System.DateTime> start_dttm, Nullable<int> week_count)
        {
            var symbolsParameter = symbols != null ?
                new ObjectParameter("symbols", symbols) :
                new ObjectParameter("symbols", typeof(string));
    
            var start_dttmParameter = start_dttm.HasValue ?
                new ObjectParameter("start_dttm", start_dttm) :
                new ObjectParameter("start_dttm", typeof(System.DateTime));
    
            var week_countParameter = week_count.HasValue ?
                new ObjectParameter("week_count", week_count) :
                new ObjectParameter("week_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XXX_sp_weekly_v1", symbolsParameter, start_dttmParameter, week_countParameter);
        }
    
        public virtual int XXX_update_daily_analysis_v1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XXX_update_daily_analysis_v1");
        }
    
        public virtual int XXX_update_daily_v1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XXX_update_daily_v1");
        }
    }
}
