//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class symbol_att
    {
        public string symbol { get; set; }
        public string name { get; set; }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public Nullable<double> market_cap { get; set; }
        public Nullable<int> market_rank { get; set; }
        public string symbol_type { get; set; }
    }
}
