//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_plan
    {
        public int test_id { get; set; }
        public string plan_name { get; set; }
        public int test_seq { get; set; }
        public string pass_list { get; set; }
        public int filter_option { get; set; }
        public string filter_att1 { get; set; }
        public string filter_att2 { get; set; }
        public string filter_att3 { get; set; }
        public string filter_att4 { get; set; }
        public string filter_att5 { get; set; }
        public string filter_desc { get; set; }
        public string remark { get; set; }
    }
}
