//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace History
{
    using System;
    using System.Collections.Generic;
    
    public partial class watch_list
    {
        public string symbol { get; set; }
        public string watch_type { get; set; }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public string company { get; set; }
    }
}
